const { io } = require('socket.io-client');
const URL='http://localhost:3000';
const mk=(n)=>new Promise(r=>{const s=io(URL,{transports:['websocket']});const st={s,n,started:false};
 s.on('connect',async()=>{await s.emitWithAck('login',{name:n,handle:n});const j=await s.emitWithAck('joinGame',{name:n});st.room=j.roomId;r(st);});
 s.on('matchStart',(d)=>{st.started=true;st.players=d.players.length;});});
const w=(ms)=>new Promise(r=>setTimeout(r,ms));
(async()=>{const a=await mk('Alice');const b=await mk('Bob');await w(300);
 a.s.emit('ready',true);b.s.emit('ready',true);await w(6500);
 console.log('same room:',a.room===b.room,'| started:',a.started&&b.started,'| players:',a.players);
 const ok=a.room===b.room&&a.started&&b.started&&a.players===2;console.log('RESULT:',ok?'PASS':'FAIL');
 a.s.close();b.s.close();process.exit(ok?0:1);})();
